config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/'      => "homes#top"   , as: "top"
  get '/about' => "homes#about" , as: "about"

  get   'user/show'          => "users#show"              , as: "users_show"
  get   'user/edit'          => "users#edit"              , as: "users_edit"
  patch 'user/edit'          => "users#update"            , as: "users_update"
  get   'user/withdrawal'    => "users#withdrawal"        , as: "withdrawal"
  patch 'user/withdrawal'    => "users#withdrawal_update" , as: "withdrawal_update"

  resources :reports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :mountain_name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :reports       
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    users_show_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]

  def new
    @report = Report.new

  end

  def create
    @report = Report.new(new_report_params)
    if @report.save
      flash[:notice] = "新規レポートを投稿しました。"
      redirect_to users_show_path
    else
      render :new
    end
  end

  def show
    @report = Report.find(params[:id])
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(uodate_report_params)
      flash[:notice] = "レポートを更新しました。"
      redirect_to users_show_path
    else
      render :edit
    end

  end

  def index
    @reports = Report.all
  end

  def destroy
    report = Report.find(params[:id])
    report.destroy
    flash[:notice] = "対象のレポートを削除しました。"
    redirect_to users_show_path
  end

  private

  def new_report_params
    params.require(:report).permit(:user_id, :title, :mountain_name, :elevation, :walking_time, :difficulty, :comment)
  end

  def uodate_report_params
    params.require(:report).permit(:user_id, :title, :mountain_name, :elevation, :walking_time, :difficulty, :comment)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = current_user
    @reports = current_user.reports
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    if user.update(user_params)
      flash[:notice] = "ユーザー情報を編集しました。"
      redirect_to users_edit_path
    else
      flash[:alert] = "ユーザー情報を編集に失敗しました。"
      render :users_edit_path
    end
  end

  def withdrawal
  end

  def withdrawal_update
    user = current_user
    user.update(is_active: false)
    reset_session
    flash[:notice] = "退会処理が完了しました"
    redirect_to top_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="center">
  <p class="text-success"><%= flash[:notice] %></p>
  <h2>やまれぽ！！で登山の感想、記録を共有しましょう！</h2>
  <div class="space"></div>
  <h4>
    やまれぽ！！では会員登録をすることで、登頂した山のデータや感想を記録し、<br>
    他のユーザーと共有する事が出来ます！<br>
    会員登録をしなくても他のユーザーのレポートは見ることが出来ます！<br>
    <div class="space"></div>
    <%= link_to "試しに見てみる",reports_path %>
  </h4>

  <div class="space"></div>

  <h3 class="text-danger">やまれぽ！！でレポートを残して、色褪せない思い出を積み重ねましょう！！</h3>

  <%=link_to "今すぐ会員登録する(無料)", new_user_registration_path, class: "btn btn-success mt-5" %>
  <p class="mt-3">※会員登録がお済みの方は、メニューよりログインしてください。</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yamarepo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-light">
      <div class="container">
        <%= link_to top_path, method: :get do %>
          <i class="fas fa-mountain fa-3x" style="color: green;"></i>
        <% end %>
        <span>登山の感想書くなら<strong>やまれぽ！！</strong></span>

        <div class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <p class="mr-5">ようこそ、<%= current_user.nickname %>さん！</p>
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                メニュー
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "マイページ", users_show_path, class: "dropdown-item" %>
                <%= link_to "新規投稿", new_report_path, class: "dropdown-item" %>
                <%= link_to "投稿一覧",reports_path , class: "dropdown-item" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "退会", withdrawal_path, class: "dropdown-item" %>
              </div>
            </div>
          <% else %>
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle mr-5" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                メニュー
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "トップ", top_path, class: "dropdown-item" %>
                <%= link_to "やまれぽ！！とは？", about_path, class: "dropdown-item" %>
                <%= link_to "無料会員登録", new_user_registration_path, class: "dropdown-item" %>
                <%= link_to "ログイン", new_user_session_path, class: "dropdown-item" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/reports/edit.html.erb
<div class="container">
  <h2>レポート編集</h2>
  <p><span class="text-danger">*</span>は入力必須項目です。</p>
  <% if @report.errors.any? %>
    <p class="text-danger">必須項目が入力されていません。</p>
  <% end%>

  <%= form_with model: @report, local: true do |f| %>

    <div class="row mt-5">
      <div class="col-sm-3">
        <%= f.label :title, "タイトル" %><span class="text-danger">*</span>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :title, size: 60 %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :mountain_name, "山の名称" %><span class="text-danger">*</span>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :mountain_name %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :elevation, "標高" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :elevation %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :walking_time, "歩行時間" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :walking_time %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :difficulty, "難易度" %>
      </div>
      <div class="col-sm-9">
        <%= f.radio_button :difficulty, '初心者向け' %>
        <%= f.label :difficulty, '初心者向け', value: "初心者向け" %><br>
        <%= f.radio_button :difficulty, '中級者向け' %>
        <%= f.label :difficulty, '中級者向け', value: "中級者向け" %><br>
        <%= f.radio_button :difficulty, '上級者向け' %>
        <%= f.label :difficulty, '上級者向け', value: "上級者向け" %><br>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :comment, "コメント" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_area :comment, size: "60x10" %>
      </div>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="row mt-3">
      <div class="col-sm-3"></div>
      <div class="col-sm-9">
        <%= f.submit "編集する" %>
      </div>
    </div>

  <% end %>

</div>

app/views/reports/index.html.erb
<div class="container">
  <h2>投稿一覧</h2>

  <table class="table">
    <tr>
      <th>タイトル</th>
      <th>山の名称</th>
      <th>投稿者<th>
    </tr>

    <% @reports.each do |report|%>
      <tr>
        <td><%= link_to "#{report.title}",report_path(report.id) %></td>
        <td><%= report.mountain_name %></td>
        <td><%= report.user.nickname %></td>
      </tr>
    <% end %>

  </table>
</div>

app/views/reports/new.html.erb
<div class="container">
  <h2>新規レポート投稿</h2>
  <p><span class="text-danger">*</span>は入力必須項目です。</p>
  <% if @report.errors.any? %>
    <p class="text-danger">必須項目が入力されていません。</p>
  <% end%>

  <%= form_with model: @report, local: true do |f| %>

    <div class="row mt-5">
      <div class="col-sm-3">
        <%= f.label :title, "タイトル" %><span class="text-danger">*</span>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :title, size: 60 %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :mountain_name, "山の名称" %><span class="text-danger">*</span>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :mountain_name %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :elevation, "標高" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :elevation %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :walking_time, "歩行時間" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :walking_time %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :difficulty, "難易度" %>
      </div>
      <div class="col-sm-9">
        <%= f.radio_button :difficulty, '初心者向け' %>
        <%= f.label :difficulty, '初心者向け', value: "初心者向け" %><br>
        <%= f.radio_button :difficulty, '中級者向け' %>
        <%= f.label :difficulty, '中級者向け', value: "中級者向け" %><br>
        <%= f.radio_button :difficulty, '上級者向け' %>
        <%= f.label :difficulty, '上級者向け', value: "上級者向け" %><br>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <%= f.label :comment, "コメント" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_area :comment, size: "60x10" %>
      </div>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="row mt-3">
      <div class="col-sm-3"></div>
      <div class="col-sm-9">
        <%= f.submit "投稿する" %>
      </div>
    </div>

  <% end %>

</div>

app/views/reports/show.html.erb
<div class="container">

  <h2>レポート</h2>

  <div class="row mt-5">
      <div class="col-sm-3">
        <p>タイトル</p>
      </div>
      <div class="col-sm-9">
        <%= @report.title %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
       <p>山の名称</p>
      </div>
      <div class="col-sm-9">
        <%=@report.mountain_name %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <p>標高</p>
      </div>
      <div class="col-sm-9">
        <%= @report.elevation %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <p>歩行時間</p>
      </div>
      <div class="col-sm-9">
        <%= @report.walking_time %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <p>難易度</p>
      </div>
      <div class="col-sm-9">
         <%= @report.difficulty %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-3">
        <p>コメント</p>
      </div>
      <div class="col-sm-9">
        <%= @report.comment %>
      </div>
    </div>

</div>

app/views/users/edit.html.erb
<div class="container">

  <h2>ユーザー情報編集</h2>
  <p class="text-success"><%= flash[:notice] %></p>
  <p class="text-danger"><%= flash[:alert] %></p>

  <%= form_with model: @user, url: users_update_path, local: true do |f| %>

    <div class="row mt-5">
      <div class="col-sm-3">
        <%= f.label :nickname, "ニックネーム" %>
      </div>
      <div class="col-sm-9">
        <%= f.text_field :nickname %>
      </div>
    </div>

     <div class="row mt-3">
      <div class="col-sm-3"></div>
      <div class="col-sm-9">
        <%= f.submit "更新する" %>
      </div>
    </div>

  <% end %>

</div>

app/views/users/show.html.erb
<div class="container">

  <h2>マイページ</h2>

  <p class="text-success"><%= flash[:notice] %></p>

  <div class="row mt-5">
    <div class="col-sm-3">
      <p>ニックネーム</p>
    </div>
    <div class="col-sm-3">
      <%= current_user.nickname %>
    </div>
    <div class="col-sm-3">
      <%= link_to "ニックネームの変更", users_edit_path %>
    </div>
  </div>

  <div class="space"></div>

  <h4>過去の投稿</h4>

  <table class="table">
    <tr>
      <th>タイトル</th>
      <th>山の名称</th>
      <th></th>
      <th></th>
    </tr>

    <% @reports.each do |report|%>
      <tr>
        <td><%= link_to "#{report.title}",report_path(report.id) %></td>
        <td><%= report.mountain_name %></td>
        <td><%= link_to "編集する", edit_report_path(report.id), class: "btn btn-sm btn-success" %></td>
        <td><%= link_to "削除する", report_path(report.id), method: :delete, data: {confirm: "削除したデータは復旧出来ません。本当に削除しますか？"}, class: "btn btn-sm btn-danger"  %></td>
      </tr>
    <% end %>

  </table>

</div>

app/views/users/withdrawal.html.erb
<div class="container center">

  <h3>本当に退会しますか？</h3>
  <h4>本サイトでの投稿、プロフィールの編集が不可能になります。</h4>
  <div class="space"></div>
  <div class="row">
      <div class="col-sm-3"></div>
      <div class="col-sm-3">
        <%= link_to "退会する", withdrawal_update_path, method: :patch, class: "btn btn-danger" %>
      </div>
      <div class="col-sm-3">
        <%= link_to "退会しない", users_show_path, class: "btn btn-primary" %>
      </div>
      <div class="col-sm-3"></div>
  </div>


</div>